server:
  port: 8085

spring:
  application:
    name: ms-repuestos

  # Conexión a MariaDB
  datasource:
    url: jdbc:mariadb://localhost:3306/db_repuestos
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:

  # JPA y Hibernate
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/